# Generated by Django 4.0 on 2021-12-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_countinstock_item_count_in_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='inventory_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='probable_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
